title: Haroon
description: "Documenting life, goals, and the occasional home truth."
author: Haroon
email: hello@hrnarf.com
url: "https://hrnarf.github.io"
baseurl: "/blog"

markdown: kramdown
permalink: /:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
